name: Deploy to EC2

on:
  push:
    branches:
      - main # Change this to match your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Transfer files to EC2 instance
        uses: nLoizar/rsync-action@v2 # Replace with the desired rsync action
        with:
          source: "dist/" # Path to your build directory
          destination: "ubuntu@${{ secrets.EC2_HOST }}:/var/www/html/timezones" # Username, host, and target path
          rsync_options: "-avz"
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Transfer files to EC2 instance
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     source: "dist/*"
      #     target: "/var/www/html/timezones"

      # - name: SSH into EC2 instance and restart server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: 22
      #     script: |
      # cd /var/www/html/change-times/dist
      # Restart your server here (e.g., using pm2 or systemctl)
