name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to match your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Transfer files to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # Your EC2 instance IP or hostname
          username: ${{ secrets.EC2_USERNAME }}  # Username to SSH into EC2 instance
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Your SSH private key (the contents of the .pem file)
          source: "dist/*"  # Path to your built React app
          target: "/var/www/html/change-times/dist"  # Path on the EC2 instance to transfer files

      - name: SSH into EC2 instance and restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /path/to/your/destination
            # Restart your server here (e.g., using pm2 or systemctl)
